# Generated by Django 5.0.6 on 2024-08-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(db_index=True, default='Anonymous', max_length=15, verbose_name='Name'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
