# Generated by Django 5.0.6 on 2024-08-31 09:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_name_alter_post_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
