# Generated by Django 5.0.6 on 2024-09-05 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='image',
        ),
    ]
